// <auto-generated />
using Exercicio_MVC_10_11_25.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercicio_MVC_10_11_25.Migrations
{
    [DbContext(typeof(APPDbContext))]
    partial class APPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exercicio_MVC_10_11_25.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Ano")
                        .HasColumnType("float");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QVeiculo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("ExibiçãoVeiculo");

                    b.HasDiscriminator<string>("QVeiculo").HasValue("Veiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Exercicio_MVC_10_11_25.Models.Carro", b =>
                {
                    b.HasBaseType("Exercicio_MVC_10_11_25.Models.Veiculo");

                    b.HasDiscriminator().HasValue("Carro");
                });

            modelBuilder.Entity("Exercicio_MVC_10_11_25.Models.Moto", b =>
                {
                    b.HasBaseType("Exercicio_MVC_10_11_25.Models.Veiculo");

                    b.HasDiscriminator().HasValue("Moto");
                });
#pragma warning restore 612, 618
        }
    }
}
