// <auto-generated />
using Exercicio_MVC_PersonagemJogo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercicio_MVC_PersonagemJogo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251114122703_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exercicio_MVC_PersonagemJogo.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Nivel")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QClasse")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("TabelaPersonagem");

                    b.HasDiscriminator<string>("QClasse").HasValue("Personagem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Exercicio_MVC_PersonagemJogo.Models.Guerreiro", b =>
                {
                    b.HasBaseType("Exercicio_MVC_PersonagemJogo.Models.Personagem");

                    b.HasDiscriminator().HasValue("Guerreiro");
                });

            modelBuilder.Entity("Exercicio_MVC_PersonagemJogo.Models.Mago", b =>
                {
                    b.HasBaseType("Exercicio_MVC_PersonagemJogo.Models.Personagem");

                    b.HasDiscriminator().HasValue("Mago");
                });
#pragma warning restore 612, 618
        }
    }
}
